# Generated by Django 5.1.2 on 2024-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('temperature_threshold', models.FloatField()),
                ('condition_alert', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('temperature_kelvin', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('feels_like_kelvin', models.FloatField()),
                ('feels_like_celsius', models.FloatField()),
                ('main_condition', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('avg_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('dominant_condition', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
    ]
